rudderlabs/rudder-sdk-node

index.js
package.json

add timer for input

---

index.d.ts
index.js
package.json
tsconfig.json

Added comments for JSDoc and generated type declaration file using it.
> Fix [#1]()

Typescript support

---

yarn.lock

Reverts rudderlabs/rudder-sdk-node#36

Revert "Bump axios from 0.21.1 to 0.21.2"

---

test.js

> Fixed Test cases failing issue
> Fix [#1]()

Test fail fix

---

index.d.ts
package.json

> ts declaration file updated
> Fix [#1]()

TS declaration file updated

---

index.d.ts
package.json

> logLevel option added in ts declaration file
> Fix [#1]()

logging option added in Ts declaration

---

index.js

I noticed that some logs are written using winston and some are written using console.log. I think it's best to standardize how logs are written. To this end, I rewrote the package to use exclusively winston for logging.  Hopefully, this is useful for ya'll!
The motivation behind this PR is that we're planning on using this package in a client-side CLI context where, in a production environment, all logging would need to be silenced. We'd like to provide our own custom logger implementation which conforms to the Winston logger interface to achieve this (e.g. inject a noop logger). If it's alright, I'd like to follow up with a second PR to add in this functionality.
- lint failed locally for master, but this branch does not introduce any new lint errors
- tests failed locally for master, …

logging exclusively with winston

---

package.json

bump version from 1.0.8 to 1.0.9

---

LICENSE.md
index.js

segment reference removed

---

package.json
yarn.lock

> Auto-changelog package updated to it’s latest version
> Fix [#1]()

Auto-changelog package updated

---

index.js
test.js

> Added channel field in Rudder payload
> Fix [#1]()

HTTP API Spec compliance update

---

index.d.ts

> Updated type declaration of createPersistenceQueue fn
> Fix [#1]()

fix: type declaration for createPersistenceQueue API

---

index.js
package-lock.json
package.json

More log syntax added
> Fix [#1]()

chore: add log syntax

---

package-lock.json
package.json

chore: fix security vulnerability

---

index.d.ts

fix: errorhandler type declaration

---

index.js

fix: lint errors

---

__tests__/loosely-validate-event/index.test.js
index.d.ts
package-lock.json
package.json
src/index.js
src/loosely-validate-event/index.js

> Resolves [SDK-460](https://linear.app/rudderstack/issue/SDK-460/fix-snyk-issues)
> Resolves [SDK-472](https://linear.app/rudderstack/issue/SDK-472/fix-types-for-nodejs-flush-method)

fix: correct type for flush & bring in loosely-validate-event package

---

CHANGELOG.md
__tests__/loosely-validate-event/index.test.js
index.d.ts
package-lock.json
package.json
sonar-project.properties
src/index.js
src/loosely-validate-event/index.js

chore(release): pulling release/2.0.5 into master

---

package-lock.json
package.json
src/Logger.js

fix: log level priority

---

CHANGELOG.md
package-lock.json
package.json
sonar-project.properties
src/Logger.js

chore(release): pulling release/2.0.6 into master

---

package-lock.json
package.json

>  Update vulnerable packages
>  Removed unused patch-package
> Fix [#1]()

fix: update vulnerable packages

---

CHANGELOG.md
package-lock.json
package.json
sonar-project.properties

chore(release): pulling release/2.0.7 into master

---

CHANGELOG.md
package-lock.json
package.json
sonar-project.properties
src/Logger.js

chore(release): pulling master into develop post release v2.0.7

---

package-lock.json
package.json

fix: upgrade axios to a safe version

---

CHANGELOG.md
package-lock.json
package.json
sonar-project.properties

chore(release): pulling release/2.0.9 into master

---

CHANGELOG.md
index.d.ts
package-lock.json
package.json
sonar-project.properties

chore(release): pulling release/2.0.10 into master

---

CHANGELOG.md
index.d.ts
package-lock.json
package.json
sonar-project.properties

chore(release): pulling master into develop post release v2.0.10

---

index.d.ts

> Allow date data type in context, traits, and properties 
> Fix [#1]()

feat: add date datatype

---

CHANGELOG.md
index.d.ts
package-lock.json
package.json
sonar-project.properties

chore(release): pulling release/2.1.0 into master

---

CHANGELOG.md
index.d.ts
package-lock.json
package.json
sonar-project.properties

chore(release): pulling master into develop post release v2.1.0

---

CODEOWNERS
package-lock.json
package.json

I've fixed all the existing dev and prod vulnerabilities. I've excluded dev dependencies from the security check.
Also, added GitHub team for code ownership.
> Fix [#1]()

fix: vulnerabilties in dev and prod dependencies
